export const CHANGE_DRAWER_MODE = 'CHANGE_DRAWER_MODE';
export const SET_MOVIE_LIST= 'SET_MOVIE_LIST';
export const SET_SELECTED_MOVIE_INFO= 'SET_SELECTED_MOVIE_INFO';
export const SET_MOVIE_COMMENTS= 'SET_MOVIE_COMMENTS';
export const REACTION_ADJUSMENTS='REACTION_ADJUSMENTS';
export const SET_WATCH_MOVIE='SET_WATCH_MOVIE';
export const SET_CHANNEL_DATA='SET_CHANNEL_DATA';